PY_TB_VHDL = [ "string_pkg.vhd", "kirsch_unsynth_pkg.vhd", "kirsch_tb.vhd" ]
OPT_EFFORT_PHYS = 0
PY_DESIGN_VHDL = [ "mem.vhd", "kirsch.vhd" ]
USER_TOOL_FLAGS = 
PART = 10M08SAE144C8G
DESIGN_ARCH = main
SH_FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm-enc /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/maxv
FREQ_MIN = 50
SIM_TOOL = MODELSIM
GENERICS_DICT = 
ECE327 = /home/ece327
SH_TB_VHDL = string_pkg.vhd kirsch_unsynth_pkg.vhd kirsch_tb.vhd
TB_ENTITY = kirsch_tb
GOAL_FREQ = 50
GOAL_PERIOD = 20
PRECISION_PART = 10M08SAE144C8GES
TCL_GENERICS_DICT = {  }
RPT_DIR = RPT
PY_FAB_SIM_LIBS = [ "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm-enc", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/maxv" ]
TCL_FAB_SIM_LIBS = { /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm-enc /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/maxv }
SH_GENERICS_DICT = 
LOGIC_SYNTH_TOOL = PRECISION_RTL
TB_ARCH = main
PY_GENERICS_DICT = [ "" ]
TCL_TB_VHDL = { string_pkg.vhd kirsch_unsynth_pkg.vhd kirsch_tb.vhd }
GUI_FLAG = -shell
NUM_TIMING_PATHS = 5
PWR_TOOL = QUARTUS
INTERACTIVE_FLAG = False
BOARD = lstep
OPT_EFFORT_LOGIC_1 = 0
OPT_EFFORT_LOGIC_2 = 0
DESIGN_ENTITY = kirsch
FAMILY_SHORT = Max10
SH_DESIGN_VHDL = mem.vhd kirsch.vhd
ASIC = False
OLD_DC_SHELL = False
OPT_EFFORT = 0
GENERICS = {  }
LIB_VHDL = util.vhd, kirsch_synth_pkg.vhd
SH_LIB_VHDL = util.vhd kirsch_synth_pkg.vhd
USE_GUI = False
TB_VHDL = string_pkg.vhd, kirsch_unsynth_pkg.vhd, kirsch_tb.vhd
SIM_SCRIPT = kirsch_tb.sim
FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/fiftyfivenm-enc, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/maxv
LOGIC_SYNTH_EXT = vhd
RPT_TDIR = RPT
FAMILY_LONG = Max 10
TCL_DESIGN_VHDL = { mem.vhd kirsch.vhd }
SPEED = 8
UWP = kirsch
LC_FAMILY_SHORT = max10
PHYS_SYNTH_TOOL = QUARTUS
PROG = uw-synth
TCL_LIB_VHDL = { util.vhd kirsch_synth_pkg.vhd }
DESIGN_VHDL = mem.vhd, kirsch.vhd
PY_LIB_VHDL = [ "util.vhd", "kirsch_synth_pkg.vhd" ]
